[package]
name = "antv-graph-wasm"
version = "0.0.1"
authors = ["antv"]
edition = "2018"
license = "MIT"
description = "A WASM binding of rust implementation for graph algorithms."
repository = "https://github.com/antvis/algorithm"
documentation = "https://observablehq.com/d/2db6b0cc5e97d8d6"
keywords = ["graph", "viz"]
categories = ["visualization"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[profile.release]
panic = 'abort'
lto = true
opt-level = 's'

[lib]
crate-type = ["cdylib"]
path = "rust-src/lib.rs"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
graph = { version = "0.3.0", features = ["serde"] }
console_error_panic_hook = "0.1"
js-sys = "0.3.51"
serde-wasm-bindgen = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-rayon = { version = "1.0", optional = true }
wee_alloc = { version = "0.4", optional = true }

[features]
parallel = ["wasm-bindgen-rayon", "wee_alloc"]